"""
generate_mac_configs.py — Generate macOS-compatible MMDetection configs.

Adapts the baseline and optimized configs for Mac by:
  - Setting device to 'mps' or 'cpu' (no CUDA)
  - Reducing batch size (Mac has less VRAM/memory)
  - Reducing training epochs (Mac is slower)
  - Disabling NCCL distributed backend
  - Disabling AMP on MPS (not fully supported)
  - Using single-process data loading (fork issues on macOS)

Usage:
    python scripts/generate_mac_configs.py --device mps
    python scripts/generate_mac_configs.py --device cpu
"""

import argparse
import os


def generate_baseline_mac_config(device='mps'):
    """Generate Mac-compatible baseline config."""
    config = f'''# Baseline Config — Mac Compatible ({device.upper()})
# Faster R-CNN + ResNet-50-FPN, reduced schedule for Mac
# Auto-generated by generate_mac_configs.py

_base_ = []

# ========================
# MODEL
# ========================
model = dict(
    type='FasterRCNN',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')
    ),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5
    ),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]
        ),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]
        ),
        loss_cls=dict(type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)
    ),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]
        ),
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=80,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0.0, 0.0, 0.0, 0.0],
                target_stds=[0.1, 0.1, 0.2, 0.2]
            ),
            reg_class_agnostic=False,
            loss_cls=dict(type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', loss_weight=1.0)
        )
    ),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7, neg_iou_thr=0.3,
                min_pos_iou=0.3, match_low_quality=True, ignore_iof_thr=-1
            ),
            sampler=dict(
                type='RandomSampler', num=256, pos_fraction=0.5,
                neg_pos_ub=-1, add_gt_as_proposals=False
            ),
            allowed_border=-1, pos_weight=-1, debug=False
        ),
        rpn_proposal=dict(
            nms_pre=2000, max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7), min_bbox_size=0
        ),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5, neg_iou_thr=0.5,
                min_pos_iou=0.5, match_low_quality=False, ignore_iof_thr=-1
            ),
            sampler=dict(
                type='RandomSampler', num=512, pos_fraction=0.25,
                neg_pos_ub=-1, add_gt_as_proposals=True
            ),
            pos_weight=-1, debug=False
        )
    ),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000, max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7), min_bbox_size=0
        ),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100
        )
    )
)

# ========================
# DATASET
# ========================
dataset_type = 'CocoDataset'
data_root = 'data/coco/'

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PackDetInputs')
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', scale=(1333, 800), keep_ratio=True),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='PackDetInputs',
         meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'scale_factor'))
]

train_dataloader = dict(
    batch_size=2,               # Keep small for Mac memory
    num_workers=0,              # macOS fork issues — use 0 workers
    persistent_workers=False,
    sampler=dict(type='DefaultSampler', shuffle=True),
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='annotations/instances_train2017.json',
        data_prefix=dict(img='train2017/'),
        filter_cfg=dict(filter_empty_gt=True, min_size=32),
        pipeline=train_pipeline
    )
)

val_dataloader = dict(
    batch_size=1,
    num_workers=0,
    persistent_workers=False,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='annotations/instances_val2017.json',
        data_prefix=dict(img='val2017/'),
        test_mode=True,
        pipeline=test_pipeline
    )
)

test_dataloader = val_dataloader

val_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annotations/instances_val2017.json',
    metric='bbox', format_only=False
)
test_evaluator = val_evaluator

# ========================
# TRAINING (reduced for Mac)
# ========================
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=4, val_interval=1)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')

optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)
)

param_scheduler = [
    dict(type='LinearLR', start_factor=0.001, by_epoch=False, begin=0, end=500),
    dict(type='MultiStepLR', by_epoch=True, milestones=[3], gamma=0.1)
]

# ========================
# RUNTIME (Mac-compatible)
# ========================
default_scope = 'mmdet'

default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=50),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', interval=1, max_keep_ckpts=2),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='DetVisualizationHook')
)

env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='spawn', opencv_num_threads=0),  # spawn for macOS
    dist_cfg=dict(backend='gloo')    # gloo instead of nccl for non-CUDA
)

log_level = 'INFO'
load_from = None
resume = False

# Visualizer config (required by mmdet)
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='DetLocalVisualizer', vis_backends=vis_backends, name='visualizer')
'''
    return config
    """Generate Mac-compatible optimized config."""
    config = f'''# Optimized Config — Mac Compatible ({device.upper()})
# Faster R-CNN + ResNet-101-PAFPN + AdamW + GIoU, reduced schedule for Mac
# Auto-generated by generate_mac_configs.py
#
# Changes from baseline:
#   1. Backbone: ResNet-50 → ResNet-101
#   2. Neck: FPN → PAFPN
#   3. Optimizer: SGD → AdamW
#   4. Scheduler: MultiStep → CosineAnnealing
#   5. Augmentation: Added multi-scale + PhotoMetricDistortion
#   6. Loss: SmoothL1 → GIoU
#   7. Epochs: 4 → 8 (2x relative to baseline)

_base_ = []

# ========================
# MODEL (Optimized)
# ========================
model = dict(
    type='FasterRCNN',
    backbone=dict(
        type='ResNet',
        depth=101,                      # CHANGE: 50 → 101
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet101')
    ),
    neck=dict(
        type='PAFPN',                   # CHANGE: FPN → PAFPN
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5
    ),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]
        ),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]
        ),
        loss_cls=dict(type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)
    ),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]
        ),
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=80,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0.0, 0.0, 0.0, 0.0],
                target_stds=[0.1, 0.1, 0.2, 0.2]
            ),
            reg_class_agnostic=False,
            loss_cls=dict(type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(
                type='GIoULoss',          # CHANGE: SmoothL1 → GIoU
                loss_weight=10.0
            )
        )
    ),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7, neg_iou_thr=0.3,
                min_pos_iou=0.3, match_low_quality=True, ignore_iof_thr=-1
            ),
            sampler=dict(
                type='RandomSampler', num=256, pos_fraction=0.5,
                neg_pos_ub=-1, add_gt_as_proposals=False
            ),
            allowed_border=-1, pos_weight=-1, debug=False
        ),
        rpn_proposal=dict(
            nms_pre=2000, max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7), min_bbox_size=0
        ),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5, neg_iou_thr=0.5,
                min_pos_iou=0.5, match_low_quality=False, ignore_iof_thr=-1
            ),
            sampler=dict(
                type='RandomSampler', num=512, pos_fraction=0.25,
                neg_pos_ub=-1, add_gt_as_proposals=True
            ),
            pos_weight=-1, debug=False
        )
    ),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000, max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7), min_bbox_size=0
        ),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100
        )
    )
)

# ========================
# DATASET (Enhanced augmentation)
# ========================
dataset_type = 'CocoDataset'
data_root = 'data/coco/'

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    # CHANGE: Multi-scale training
    dict(
        type='RandomResize',
        scale=[(1333, 480), (1333, 800)],
        keep_ratio=True
    ),
    dict(type='RandomFlip', prob=0.5),
    # CHANGE: Color augmentation
    dict(
        type='PhotoMetricDistortion',
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18
    ),
    dict(type='PackDetInputs')
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', scale=(1333, 800), keep_ratio=True),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='PackDetInputs',
         meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'scale_factor'))
]

train_dataloader = dict(
    batch_size=2,               # Keep small for Mac memory
    num_workers=0,              # macOS fork issues — use 0 workers
    persistent_workers=False,
    sampler=dict(type='DefaultSampler', shuffle=True),
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='annotations/instances_train2017.json',
        data_prefix=dict(img='train2017/'),
        filter_cfg=dict(filter_empty_gt=True, min_size=32),
        pipeline=train_pipeline
    )
)

val_dataloader = dict(
    batch_size=1,
    num_workers=0,
    persistent_workers=False,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='annotations/instances_val2017.json',
        data_prefix=dict(img='val2017/'),
        test_mode=True,
        pipeline=test_pipeline
    )
)

test_dataloader = val_dataloader

val_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annotations/instances_val2017.json',
    metric='bbox', format_only=False
)
test_evaluator = val_evaluator

# ========================
# TRAINING (reduced for Mac, but 2x baseline)
# ========================
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=8, val_interval=1)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')

# CHANGE: AdamW optimizer
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(
        type='AdamW',
        lr=0.0001,
        betas=(0.9, 0.999),
        weight_decay=0.05
    ),
    clip_grad=dict(max_norm=35, norm_type=2)
)

# CHANGE: Cosine annealing
param_scheduler = [
    dict(type='LinearLR', start_factor=0.001, by_epoch=False, begin=0, end=500),
    dict(
        type='CosineAnnealingLR',
        by_epoch=True, begin=1, end=8,
        eta_min=1e-6
    )
]

# ========================
# RUNTIME (Mac-compatible)
# ========================
default_scope = 'mmdet'

default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=50),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', interval=2, max_keep_ckpts=2),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='DetVisualizationHook')
)

env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='spawn', opencv_num_threads=0),  # spawn for macOS
    dist_cfg=dict(backend='gloo')    # gloo instead of nccl for non-CUDA
)

log_level = 'INFO'
load_from = None
resume = False

# Visualizer config (required by mmdet)
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='DetLocalVisualizer', vis_backends=vis_backends, name='visualizer')

# NOTE: AMP disabled on Mac — MPS does not fully support mixed precision
# On CUDA systems, uncomment:
# optim_wrapper.update(dict(type='AmpOptimWrapper', loss_scale='dynamic'))
'''
    return config


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--device', default='mps', choices=['mps', 'cpu'])
    args = parser.parse_args()

    os.makedirs('configs', exist_ok=True)

    # Baseline
    baseline = generate_baseline_mac_config(args.device)
    baseline_path = 'configs/baseline_faster_rcnn_r50_fpn_mac.py'
    with open(baseline_path, 'w') as f:
        f.write(baseline)
    print(f"Generated: {baseline_path}")

    # Optimized
    optimized = generate_optimized_mac_config(args.device)
    optimized_path = 'configs/optimized_faster_rcnn_r101_pafpn_mac.py'
    with open(optimized_path, 'w') as f:
        f.write(optimized)
    print(f"Generated: {optimized_path}")


if __name__ == '__main__':
    main()
